---
title: "HLA Class prediction"
author: "Hem Gurung, Ph.D."
date: "2/23/2019"
output: html_document
---
knit: (function(input_file, encoding) {
 out_dir <- 'docs';
 rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This project builds a simple binomial logistic regression model to predict whether a given peptide belongs to class I or class II based on its mass, length, m/z, and retention time values.

```{r}
setwd("/Users/hem/Desktop/myfolder")

# read the dataset

dataset <- read.csv("all_pep_final.csv", header = T)
dim(dataset)
names(dataset)
head(dataset)


# remove unwanted columns
drop <- c("Peptide", "X.10lgP", "ppm", "Area", "Fraction", "Scan", "Source.File", "X.Spec", "Accession")
dataset <- dataset[, !names(dataset) %in% drop]

# Check if there is any NA in the dataset 
sapply(dataset, function(x) sum(is.na(x)))
head(dataset)

# Rename Class I as 1 and class II as 0
dataset$HLA_Class <- ifelse(dataset$HLA_Class == "Class I", 1, 0)
head(dataset)
table(dataset$HLA_Class) # class bias with more proportion in class I data

# treat class bias and split dataset into train and validate sets
all_ones <- dataset[which(dataset$HLA_Class == 1), ]
all_zeros <- dataset[which(dataset$HLA_Class == 0), ]
dim(all_ones)
dim(all_zeros)

set.seed(123)
training_indices_ones <- sample(1:nrow(all_ones), 0.8*nrow(all_zeros))
training_indices_zeros <- sample(1:nrow(all_zeros), 0.8*nrow(all_zeros))

training_ones <- all_ones[training_indices_ones, ]
training_zeros <- all_zeros[training_indices_zeros, ]
train <- rbind(training_ones, training_zeros)
dim(train) # rows doubled


# Create validation dataset
validate_ones <- all_ones[-training_indices_ones, ]
validate_zeros <- all_zeros[-training_indices_zeros, ]
validate <- rbind(validate_ones, validate_zeros)
dim(validate)

# Fit a binomial regression model
model <- glm(HLA_Class ~., family = binomial(link = 'logit'), data = train)

summary(model)

# Run anova to analyze the table of deviance

anova(model, test = "Chisq")

# assess the predictive ability of the model
fitted.results <- predict(model, newdata = validate, type = "response")
fitted.results <- ifelse(fitted.results >0.5, 1, 0)
misClassificationError <- mean(fitted.results != validate$HLA_Class)
print(paste("Accuracy", 1-misClassificationError))

# Interpolate the classification of peptides 
validate$predicted_HLA_Class <- fitted.results
validate

# plot ROC curve
library(ROCR)
pr <- prediction(fitted.results, validate$HLA_Class)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

# calculate AUC
AUC <- performance(pr, measure = "auc")
AUC <- AUC@y.values[[1]]
AUC
```